modLoader = "javafml"
loaderVersion = "[2,)"
license = "CC0-1.0"

[[mods]]
modId = "insight"
version = "${version}"
displayName = "Insight"
logoFile = "assets/insight/icon.png"
authors = "chan1"
description = '''
See the world with clarity, 3d tooltips show entity health, dropped items, crop growth, and bed timers
'''

[[dependencies.insight]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.insight]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.insight]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "insight.mixins.json"
